### ISSUE TITLE
[Bug]: How to get the UI deployed 

### ISSUE THREAD

**Issue by jseiser** [memgraph/helm-charts#9]
### Contact Details

justinseiser@gmail.com

### What happened?

We are currently using memgraph in a project.  Locally teh developers utilize the memgraph-platform image, and we really want to be able to demo out the UI in this project.

Is it as simple as overriding the default image to be memgraph-platform, and configure the service to expose a UI port, and creating an ingress?

Is it possible to deploy the UI separate from the DB itself?

### Chart type

Standalone

### Chart version

0.1.0

### Environment

Amazon Web Services

**Comment by antejavor** [comment]
Hi @jseiser, so the Memgraph Lab is currently closed-source. 

Why do you need a Memgraph lab inside the Kubernetes cluster?  

Memgraph lab was designed to be used as a standalone application where you can connect to different Memgraph instances: [Memgraph LAB](https://memgraph.com/lab )


But to answer your question: 

**Is it possible to deploy the UI separately from the DB itself?**

No, since it is closed-source at the moment, but this will probably change in the future. There is a hacky way to achieve this by fiddling with Docker images but it is not straightforward action. 

**Is it as simple as overriding the default image to be memgraph-platform, and configure the service to expose a UI port, and creating an ingress?**

Almost, the issue arises due to Memgraph Console running in the terminal by default (and failing due to not being able to connect to tty), this crashes the container in Kubernetes.  We are in the process of changing this in the upcoming weeks. Once that is cleared, deploying MemgraphDB and the Memgraph platform should be almost identical,

Deploying Memgraph Platform and Memgraph Mage in Kubernetes are two next improvements we are planning for this repo.

**Comment by jseiser** [comment]
Ante,

The real desire is being able to demonstrate all the "cool things" that our
developers are doing with memgraph to the various shareholders of this RFC
we are working on.

Being able to port-forward and then remotely connect the UI will work as
well

**Comment by antejavor** [comment]
Cool than just installing Memgraph LAB locally and connecting to a remote instance, that is the way to go.
